# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc

# IP: ip/RAM_FIFO1/RAM_FIFO1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_FIFO1 || ORIG_REF_NAME==RAM_FIFO1} -quiet] -quiet
