# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.srcs/sources_1/ip/clk_wiz_400/clk_wiz_400.xci
# IP: The module: 'clk_wiz_400' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/clk_wiz_400/clk_wiz_400_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_400'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/clk_wiz_400/clk_wiz_400.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/clk_wiz_400/clk_wiz_400_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.srcs/sources_1/ip/clk_wiz_400/clk_wiz_400.xci
# IP: The module: 'clk_wiz_400' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/clk_wiz_400/clk_wiz_400_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/clk_wiz_400/clk_wiz_400.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/clk_wiz_400/clk_wiz_400_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
