# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.srcs/sources_1/ip/arccos_data/arccos_data.xci
# IP: The module: 'arccos_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/arccos_data/arccos_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arccos_data'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.srcs/sources_1/ip/arccos_data/arccos_data.xci
# IP: The module: 'arccos_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/bsc_mandelbulb1/bsc_mandelbulb1.gen/sources_1/ip/arccos_data/arccos_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arccos_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
